[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true

[program:scheduler]
command=/bin/sh -c "while true; do php /var/www/html/artisan schedule:run; sleep 60; done"
autorestart=true
